# Use docker to run the tests
sudo: required

language: c

services:
  - docker

env:

  matrix:
    # Test with multiple Nginx versions
    # Source: http://nginx.org/en/download.html

    # Alpine uses musl c library
    - NGINX_VERSION=1.9.15  BUILD_DISTRO=alpine COMPILER=gcc
    - NGINX_VERSION=1.10.3  BUILD_DISTRO=alpine COMPILER=gcc
    - NGINX_VERSION=1.11.13 BUILD_DISTRO=alpine COMPILER=gcc
    - NGINX_VERSION=1.12.0  BUILD_DISTRO=alpine COMPILER=gcc
    - NGINX_VERSION=1.13.2  BUILD_DISTRO=alpine COMPILER=gcc

    # Debian uses glibc c library run with GNU C compiler
    - NGINX_VERSION=1.9.15  BUILD_DISTRO=debian COMPILER=gcc
    - NGINX_VERSION=1.10.3  BUILD_DISTRO=debian COMPILER=gcc
    - NGINX_VERSION=1.11.13 BUILD_DISTRO=debian COMPILER=gcc
    - NGINX_VERSION=1.12.0  BUILD_DISTRO=debian COMPILER=gcc
    - NGINX_VERSION=1.13.2  BUILD_DISTRO=debian COMPILER=gcc
    
    # Run also with clang compiler
    - NGINX_VERSION=1.9.15  BUILD_DISTRO=debian COMPILER=clang
    - NGINX_VERSION=1.10.3  BUILD_DISTRO=debian COMPILER=clang
    - NGINX_VERSION=1.11.13 BUILD_DISTRO=debian COMPILER=clang
    - NGINX_VERSION=1.12.0  BUILD_DISTRO=debian COMPILER=clang
    - NGINX_VERSION=1.13.2  BUILD_DISTRO=debian COMPILER=clang
before_script:
  - docker-compose -v

script:
  # Build image with nginx and tests included
  # Use travis_retry to avoid errors from network timeouts
  - travis_retry docker build -t ngx-redis-test:$BUILD_DISTRO -f t/misc/test-$BUILD_DISTRO.Dockerfile --build-arg NGINX_VERSION=1.9.15 --build-arg CC=$COMPILER .

  # Start services for the tests
  - docker-compose -f t/misc/docker-compose-services.yml up -d

  # Run the tests
  - docker run -it --rm --network="container:ngx_redis_server" ngx-redis-test:$BUILD_DISTRO sh -c "nginx -v && prove -r t"