version: '2'

services:
  nginx-alpine:
    build:
      context: .
      dockerfile: ./t/misc/test-alpine.dockerfile
    volumes:
      - ./t:/build/t:rw,cached
    environment:
      TEST_NGINX_REDIS_HOST: redis
      TEST_NGINX_REDIS_PORT: 6379
      TEST_NGINX_REDIS_AUTH_ENABLED_HOST: redis-auth-enabled
      TEST_NGINX_REDIS_AUTH_ENABLED_PORT: 6380
      TEST_NGINX_REDIS_AUTH_ENABLED_PASS: password
    network_mode: "service:redis"

  
  nginx-debian:
    build:
      context: .
      dockerfile: ./t/misc/test-debian.dockerfile
    environment:
      TEST_NGINX_REDIS_HOST: redis
      TEST_NGINX_REDIS_PORT: 6379
      TEST_NGINX_REDIS_AUTH_ENABLED_HOST: redis-auth-enabled
      TEST_NGINX_REDIS_AUTH_ENABLED_PORT: 6379
      TEST_NGINX_REDIS_AUTH_ENABLED_PASS: password
    network_mode: "service:redis"


  redis:
    image: redis

  redis-auth-enabled:
    image: redis
    command: redis-server --port 6380 --requirepass password
    network_mode: "service:redis"