version: '2'

services:
  redis:
    image: redis
    container_name: ngx_redis_server

  redis-auth-enabled:
    image: redis
    command: redis-server --port 6380 --requirepass password
    network_mode: "service:redis"